- .travis.yml
- 3.1/Dockerfile
- 3.1/docker-entrypoint.sh
- 3.1/passenger/Dockerfile
- 3.2/Dockerfile
- 3.2/docker-entrypoint.sh
- 3.2/passenger/Dockerfile
Hello,
Redmine 3.1 and 3.2 are out now, and ready for release.  I've added folders and Dockerfiles for 3.1 and 3.2, as well as update the .travis.yml to test them.  I think the stackbrew script has to be updated as well, but I didn't touch that, since I'm not sure how it works.
> Add Dockerfiles for 3.1 and 3.2 releases

- 2.6/Dockerfile
- 3.0/Dockerfile
- 3.1/Dockerfile
- 3.2/Dockerfile
- Dockerfile.template
See also docker-library/official-images#1420.
> Fix "gpg" usage to stop relying on deprecated and insecure behavior

- 3.1/Dockerfile
- 3.2/Dockerfile
- 3.3/Dockerfile
- Dockerfile.template
Redmine provides https for downloads, but links to http on their website.
> use "https" for communications with "www.redmine.org"

- 3.1/docker-entrypoint.sh
- 3.2/docker-entrypoint.sh
- 3.3/docker-entrypoint.sh
- docker-entrypoint.sh
This adds explicit support for the following:
- `REDMINE_DB_MYSQL_FILE`
- `REDMINE_DB_POSTGRES_FILE`
- `REDMINE_DB_PORT_FILE`
- `REDMINE_DB_USERNAME_FILE`
- `REDMINE_DB_PASSWORD_FILE`
- `REDMINE_DB_DATABASE_FILE`
- `REDMINE_DB_ENCODING_FILE`
- `REDMINE_SECRET_KEY_BASE_FILE`
See also https://github.com/docker-library/wordpress/pull/186 and https://github.com/docker-library/postgres/pull/225
> Add "file_env" support, especially for Docker secrets

- 3.1/docker-entrypoint.sh
- 3.2/docker-entrypoint.sh
- 3.3/docker-entrypoint.sh
- docker-entrypoint.sh
Fixes permissions for key directories upon startup of Redmine - in case the have been changed. Logic for this has been taken directly from the [RedmineInstall Wiki](http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Step-8-File-system-permissions).
> Fixes directory permissions at startup

- 3.1/passenger/Dockerfile
- 3.2/passenger/Dockerfile
- 3.3/passenger/Dockerfile
- Dockerfile-passenger.template
> Explicitly invoke "passenger-config download-nginx-engine" during image build time to avoid the runtime trying to download NGINX

- docker-entrypoint.sh
Redmine has a rake task to iterate all plugins and perform migration steps. The reference can be found [here](https://www.redmine.org/projects/redmine/wiki/Plugins).
This will make it easier to integrate Plugins in the docker container. The user only has to mount a host folder with all the required plugins to /usr/src/redmine/plugins. With this rake task in place, all steps for making the plugins available are taken, though there may still be dependencies for the plugin that have to be installed first. In order to automate dependency installation, it might be a good idea to expect a bash script with the same name as the plugin that can takes care of the dependencies.
> Migrate plugins on startup of redmine

- 3.1/Dockerfile
- 3.1/docker-entrypoint.sh
- 3.2/Dockerfile
- 3.2/docker-entrypoint.sh
- 3.3/Dockerfile
- 3.3/docker-entrypoint.sh
- 3.4/Dockerfile
- 3.4/docker-entrypoint.sh
- Dockerfile.template
- docker-entrypoint.sh
Reference issue #74 
- Update Dockerfile to create adapter specific `Gemfile.lock.${adapter}` file.
- Update `docker-entrypoint.sh` to copy adapter specific file to Gemfile.lock
> create and use db adapter specific Gemfile.lock files to fix issue #74

- 3.1/docker-entrypoint.sh
- 3.2/docker-entrypoint.sh
- 3.3/docker-entrypoint.sh
- 3.4/docker-entrypoint.sh
- docker-entrypoint.sh
Users can install additional gems using Gemfile.local and/or
plugins/*/{Gemfile,PluginGemfile}.
> Install additional gems

- 3.1/Dockerfile
- 3.2/Dockerfile
- 3.3/Dockerfile
- 3.4/Dockerfile
- Dockerfile.template
- generate-stackbrew-library.sh
```diff
diff --git a/dev/fd/63 b/dev/fd/62
--- a/dev/fd/63
+++ b/dev/fd/62
@@ -1,11 +1,12 @@
-# this file is generated via https://github.com/docker-library/redmine/blob/083fd3c293a01cf19bcb3c24a05db31f6a6b05bb/generate-stackbrew-library.sh
+# this file is generated via https://github.com/docker-library/redmine/blob/10bdb805ef3e5a3edd4cd1a79369ae2bfdc6e3f9/generate-stackbrew-library.sh
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/redmine.git
Tags: 3.4.2, 3.4, 3, latest
-GitCommit: bcaee7ff541b6ff01b7593e44444b3d561f67472
+Architectures: amd64, arm32v5, arm32v7, arm64v8, i386, ppc64le, s390x
+GitCommit: 10bdb805ef3e5a3edd4cd1a79369ae2bfdc6e3f9
Directory: 3.4
Tags: 3.4.2-passenger, …
```
> Add same arches as ruby, Gosu & tini bump

- 3.2/docker-entrypoint.sh
- 3.3/docker-entrypoint.sh
- 3.4/docker-entrypoint.sh
- docker-entrypoint.sh
This `bundle exec` fails when a new plugin including Gemfile is placed.
Because `bundle install` has not been executed yet.
This code seems less necessary.
(#88 may be derived from the same cause)
> Delete the process to get the database adapter.

- 3.2/docker-entrypoint.sh
- 3.3/docker-entrypoint.sh
- 3.4/docker-entrypoint.sh
- docker-entrypoint.sh
Fixes #94.
It has the same overall effect as the [docs](https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Step-8-File-system-permissions), but only one permission change per file to be nicer to disks.
```console
chmod -R 755 files log tmp public/plugin_assets
find files log tmp public/plugin_assets -type f -exec chmod -x {} +
```
> Fix chmod to only add execute to directories

- 3.2/Dockerfile
- 3.2/docker-entrypoint.sh
- 3.3/Dockerfile
- 3.3/docker-entrypoint.sh
- 3.4/Dockerfile
- 3.4/docker-entrypoint.sh
- Dockerfile.template
- docker-entrypoint.sh
So, Redmine now has proper support for Microsoft SQL Server, which even runs on Linux and [Docker](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker) now. I attempted to add support for this, and would appreciate feedback. I'm new to this stuff.
While building the Docker images, I had problems with `ha.pool.sks-keyservers.net` being slow and unreliable, so I'm also proposing changes to use the MIT server instead, which worked much more reliably for me.
> Add Microsoft SQL server adapter

- .travis.yml
- 3.3/Dockerfile
- 3.4/Dockerfile
- Dockerfile.template
Backporting https://github.com/matomo-org/docker/issues/104#issuecomment-394511396
> Update Debain base to stretch

- 3.3/docker-entrypoint.sh
- 3.4/docker-entrypoint.sh
- docker-entrypoint.sh
Also only `chmod` when not it is not the right permissions. This removes the `ugo-x,u+rwX,go+rX,go-w`, which makes it much easier to understand.
This does not change the `chown` to user only like the mariadb and percona changes do since the upstream [docs](https://www.redmine.org/projects/redmine/wiki/RedmineInstall#Step-8-File-system-permissions) recommend `chown redmine:redmine`.  Should I expand the finds to fix group owner too?
Same as https://github.com/docker-library/rabbitmq/pull/281, https://github.com/docker-library/mariadb/pull/203, https://github.com/docker-library/percona/pull/69
> Only chown things in the entrypoint that are not already owned by redmine

- 3.3/Dockerfile
- 3.4/Dockerfile
- Dockerfile.template
This should fix #138, and _might_ fix #137 -- more testing required (not 100% sure we've completely reproduced all the failure modes we're seeing in #137, especially around `/usr/local/bundle/config`).
@wglambert what's the easiest way for me to help you test this and make sure it fixes at least the things you managed to reproduce?  Do you need me to push it somewhere, or can you build it from here?
I guess realistically, anyone looking to help test this should be able to do so with something like this:
```console
$ docker build --pull -t redmine:3.4 https://github.com/infosiftr/redmine.git#home-redmine:3.4
```
(and then use that now-locally-built `redmine:3.4` image in your `docker-compose.yml`, etc.)
> Pre-create /home/redmine and set wide permissions on it

- 3.3/Dockerfile
- 3.4/Dockerfile
- Dockerfile.template
Builds on #136, #141
Fixes #137
Tested (successfully) via:
```console
$ mkdir oh-no
$ echo "gem 'l'" > oh-no/Gemfile
$ docker run -it --rm -v "$PWD/oh-no":/usr/src/redmine/plugins/oh-no:ro redmine:3.4
$ docker run -it --rm -v "$PWD/oh-no":/usr/src/redmine/plugins/oh-no:ro --user 1000:1000 redmine:3.4
```
> Adjust permissions further for arbitrary user even in the face of plugins with Gemfiles

- 4.0/alpine/Dockerfile
- 4.1/alpine/Dockerfile
- Dockerfile-alpine.template
[bazaar](https://bazaar.canonical.com/) has been replaced by [breezy](https://www.breezy-vcs.org/) which hasn't it made out of [testing](https://pkgs.alpinelinux.org/packages?name=breezy&branch=edge) for 3.13.
This was the only blocker for upgrading Alpine.
> Update to Alpine 3.12 and drop bzr

- Dockerfile-alpine.template
- Dockerfile-debian.template
- update.sh
md5 is insecure, and for the latest releases only .sha256 files are
provided on redmine.org, thus the update.sh fails when downloading .md5
files.
> Use sha256 for checksumming

- 4.0/alpine/Dockerfile
- 4.1/alpine/Dockerfile
- Dockerfile-alpine.template
The main issue is that nokogiri tries to install the `x86_64-linux` binary which is linked to glibc. https://github.com/sparklemotion/nokogiri/issues/2075
This does not work well on musl-libc based systems like Alpine. There might be [a fix at some point in the future](https://github.com/rubygems/rubygems/issues/3174) but up to now it still breaks.
> Avoid glibc dependency

- 4.0/Dockerfile
- 4.0/alpine/Dockerfile
- 4.1/Dockerfile
- 4.1/alpine/Dockerfile
- 4.2/Dockerfile
- 4.2/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
rails 5.2.5 got rid of mimemagic dependency:
https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/
use packaged gosu & tini for debian based images
> shared-mime-info not needed anymore

- 4.0/Dockerfile
- 4.1/Dockerfile
- 4.2/Dockerfile
- Dockerfile-debian.template
- update.sh
* Fixes #225.
* The previously failing attachment-related tests are now passing.
* There are no other tests failing (at least on our CI based on this image).
> Allow ImageMagick to read ghostscript

- generate-stackbrew-library.sh
Note: thanks to Alpine 3.13 not being supported anymore, this fails to run, so I'm running it locally against an older commit so it can appropriately scrape the parent arches for one last push with tags before we update the Alpine and Debian versions.
As discussed in #246 and #249.
> Add suite aliases

- 4.0/Dockerfile
- 4.0/alpine/Dockerfile
- 4.1/Dockerfile
- 4.1/alpine/Dockerfile
- 4.2/Dockerfile
- 4.2/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- generate-stackbrew-library.sh
> Update to Debian Bullseye, Alpine 3.15

- 4.1/Dockerfile
- 4.1/alpine/Dockerfile
- 4.2/Dockerfile
- 4.2/alpine/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- update.sh
See https://www.redmine.org/news/134
Closes #256
(I don't _love_ the implementation here, especially the sha256 scraping, but it'll do for now so we can get this security release out.)
> Update to 4.2.4 and 4.1.6 security releases

- 4.2/Dockerfile
- 5.0/Dockerfile
- Dockerfile-debian.template
Tested and verified on `arm32v7` (but the failures are similar across at least `arm32v5`, `ppc64le`, `s390x`).
> Add "xz" to fix build on many architectures

- 4.2/alpine/Dockerfile
- 4.2/alpine/docker-entrypoint.sh
- 4.2/docker-entrypoint.sh
- 5.0/alpine/Dockerfile
- 5.0/alpine/docker-entrypoint.sh
- 5.0/docker-entrypoint.sh
- Dockerfile-alpine.template
- docker-entrypoint.sh
This should result in at most two invocations of `find` (as opposed to five), on a set of directories that might include a really huge amount of small files.
Refs #268
> Update entrypoint to combine "find" invocations

- 4.2/alpine/docker-entrypoint.sh
- 4.2/docker-entrypoint.sh
- 5.0/alpine/docker-entrypoint.sh
- 5.0/docker-entrypoint.sh
- docker-entrypoint.sh
> Skip (possibly expensive) chown/chmod of "files" if the top-level is already owned by "redmine" and permissions are "755"

- 5.1/alpine3.18/Dockerfile
- 5.1/bookworm/Dockerfile
- versions.json
- versions.sh
Redmine 5.1 can use Ruby 3.2 :tada:: https://www.redmine.org/projects/redmine/wiki/redmineinstall
This pull-request makes us using redmine-5.1 on ruby-3.2.
- Mainly changes are ~~7d1d1f1c4ab5de3d632f5eacea93fb4e841f960d~~ 58b7f5e708ad8c7c08dbb32912888cd52a572103 .
- Other commit ( ~~19a761216ef803244f8a98d0474d697f3f473f01~~ dd3e3aa0bfed505380eb13e814dce0dddb55cf80 ) runs `./update.sh` .
> Use ruby-3.2 for redmine-5.1

- 5.0/bookworm/Dockerfile
- 5.1/bookworm/Dockerfile
- Dockerfile-debian.template
Build test with `--platform=linux/s390x` worked successfully (and reproduced the failure when unchanged).
Failing build output:
```console
+ gosu redmine bundle install --jobs 16
...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /usr/local/bundle/gems/sqlite3-1.6.9/ext/sqlite3
/usr/local/bin/ruby extconf.rb
Building sqlite3-ruby using packaged sqlite3.
Extracting sqlite-autoconf-3440200.tar.gz into
tmp/powerpc64le-linux-gnu/ports/sqlite3/3.44.2... OK
Running 'configure' for sqlite3 3.44.2... OK
Running 'compile' for sqlite3 3.44.2... OK
Running 'install' for sqlite3 3.44.2... OK
Activating sqlite3 3.44.2 (from
/usr/local/bundle/gems/sqlite3-1.6.9/ports/powerpc64le-linux-gnu/sqlite3/3.44.2)...
Could not configure the build properly (pkg_config). …
```
> Add missing build dependency to fix 5.1 builds on s390x and ppc64le

- 5.0/bookworm/Dockerfile
- 5.1/bookworm/Dockerfile
- Dockerfile-debian.template
The `mips64le` `gosu` binary from Debian bookworm packages fails to run with this error:
```console
fatal error: AllThreadsSyscall6 results differ between threads; runtime corrupted
```
aka: https://github.com/golang/go/issues/56426. See also https://github.com/tianon/gosu/pull/121
This also adds `libxml2-dev` and `libxslt-dev` to fix the `nokogiri` gem on architectures where there isn't a native gem (like mips64le) and `nokogiri` attempts to build its own vendored versions of them. The two lib packages and deps will be correctly kept or purged by the `apt-mark` dance.
```console
Building Nokogiri with a packaged version of libxml2-2.11.6.
Configuration options: --host\=mips64el-unknown-linux-abi64 --enable-static
--disable-shared …
```
> Fix mips64le build errors

- 5.0/alpine3.19/Dockerfile
- 5.0/alpine3.19/docker-entrypoint.sh
- 5.0/alpine3.20/Dockerfile
- 5.0/alpine3.20/docker-entrypoint.sh
- 5.0/bookworm/Dockerfile
- 5.1/alpine3.19/Dockerfile
- 5.1/alpine3.19/docker-entrypoint.sh
- 5.1/alpine3.20/Dockerfile
- 5.1/alpine3.20/docker-entrypoint.sh
- 5.1/bookworm/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
- apply-templates.sh
See https://github.com/docker-library/postgres/pull/1246 for more details/discussion.
> Replace `su-exec` with `gosu`

- 5.0/alpine3.19/docker-entrypoint.sh
- 5.0/alpine3.20/docker-entrypoint.sh
- 5.0/bookworm/docker-entrypoint.sh
- 5.1/alpine3.19/docker-entrypoint.sh
- 5.1/alpine3.20/docker-entrypoint.sh
- 5.1/bookworm/docker-entrypoint.sh
- docker-entrypoint.sh
Support for Passenger was removed in 5.0+, and all older versions are now gone/EOL so this code is reasonable to remove.
Technically, this was the only _official_ usage of `tini` in the image, so we could make an argument for removing that as well, but maybe it's worth keeping in since it _is_ likely useful for a lot of the strange things that Redmine might do for users who might need it?
> Remove leftover `passenger` references

- 5.0/alpine3.19/Dockerfile
- 5.0/alpine3.20/Dockerfile
- 5.0/bookworm/Dockerfile
- 5.1/alpine3.19/Dockerfile
- 5.1/alpine3.20/Dockerfile
- 5.1/bookworm/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
> Use existing redmine env var to log to stdout

- 5.0/alpine3.20/Dockerfile
- 5.0/alpine3.21/Dockerfile
- 5.0/bookworm/Dockerfile
- 5.1/alpine3.20/Dockerfile
- 5.1/alpine3.21/Dockerfile
- 5.1/bookworm/Dockerfile
- 6.0/alpine3.20/Dockerfile
- 6.0/alpine3.21/Dockerfile
- 6.0/bookworm/Dockerfile
- Dockerfile-alpine.template
- Dockerfile-debian.template
```console
+ gosu redmine bundle install --jobs 4
...
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /usr/local/bundle/gems/psych-5.2.2/ext/psych
/usr/local/bin/ruby extconf.rb
checking for pkg-config for yaml-0.1... not found
checking for yaml.h... no
yaml.h not found
*** extconf.rb failed ***
```
Refs: https://github.com/docker-library/ruby/pull/493
> Add missing dev that was unintentionally included in slim and alpine ruby images

- 5.0/alpine3.20/docker-entrypoint.sh
- 5.0/alpine3.21/docker-entrypoint.sh
- 5.0/bookworm/docker-entrypoint.sh
- 5.1/alpine3.20/docker-entrypoint.sh
- 5.1/alpine3.21/docker-entrypoint.sh
- 5.1/bookworm/docker-entrypoint.sh
- 6.0/alpine3.20/docker-entrypoint.sh
- 6.0/alpine3.21/docker-entrypoint.sh
- 6.0/bookworm/docker-entrypoint.sh
- docker-entrypoint.sh
Fixes https://github.com/docker-library/redmine/issues/353
This still needs testing -- ideally we'd add some automated tests, maybe even for _all_ our supported database adapters, but that's not totally trivial.
(I have something locally for MySQL that I apparently was working on back in 2021, but it doesn't run successfully right now regardless of the issue this fixes, and I have no memory of writing it. :joy:)
> Remove quoting from `adapter:` in `database.yml`

- 5.0/alpine3.20/Dockerfile
- 5.0/alpine3.20/docker-entrypoint.sh
- 5.0/alpine3.21/Dockerfile
- 5.0/alpine3.21/docker-entrypoint.sh
- 5.0/bookworm/Dockerfile
- 5.0/bookworm/docker-entrypoint.sh
- 5.1/alpine3.20/Dockerfile
- 5.1/alpine3.20/docker-entrypoint.sh
- 5.1/alpine3.21/Dockerfile
- 5.1/alpine3.21/docker-entrypoint.sh
- 5.1/bookworm/Dockerfile
- 5.1/bookworm/docker-entrypoint.sh
- 6.0/alpine3.20/docker-entrypoint.sh
- 6.0/alpine3.21/docker-entrypoint.sh
- 6.0/bookworm/docker-entrypoint.sh
- Dockerfile-alpine.template
- Dockerfile-debian.template
- docker-entrypoint.sh
Rails 7.1-7.2 deprecated/removed `config/secrets.yml` usage and instead use `credentials`, so our generated `secrets.yml` is no longer used (which is the cause of https://github.com/docker-library/redmine/issues/349).
Rails 7.2 is used in Redmine 6.0+. Rails 6.1 is used in Redmine 5.0 and 5.1. Rails 7.2 and 6.1 both support the `SECRET_KEY_BASE` environment variable, so let's use that instead. Users can continue to use the `REDMINE_SECRET_KEY_BASE` or `REDMINE_SECRET_KEY_BASE_FILE` variables or swap to `SECRET_KEY_BASE`.
Fixes https://github.com/docker-library/redmine/issues/349
---
See removals and deprecations:
https://guides.rubyonrails.org/7_1_release_notes.html
https://guides.rubyonrails.org/7_2_release_notes.html
> Drop creating secrets.yml and just use `SECRET_KEY_BASE` env

- 5.0/alpine3.20/Dockerfile
- 5.0/alpine3.20/docker-entrypoint.sh
- 5.0/alpine3.21/Dockerfile
- 5.0/alpine3.21/docker-entrypoint.sh
- 5.0/bookworm/Dockerfile
- 5.0/bookworm/docker-entrypoint.sh
- 5.1/alpine3.20/Dockerfile
- 5.1/alpine3.20/docker-entrypoint.sh
- 5.1/alpine3.21/Dockerfile
- 5.1/alpine3.21/docker-entrypoint.sh
- 5.1/bookworm/Dockerfile
- 5.1/bookworm/docker-entrypoint.sh
- 6.0/alpine3.20/Dockerfile
- 6.0/alpine3.20/docker-entrypoint.sh
- 6.0/alpine3.21/Dockerfile
- 6.0/alpine3.21/docker-entrypoint.sh
- 6.0/bookworm/Dockerfile
- 6.0/bookworm/docker-entrypoint.sh
- Dockerfile.template
- docker-entrypoint.sh
Create and fix permissions on the `public/assets` directory. I think this is only used in 6+, but it should be harmless/unused in `5.x`.
Also fix the "$filesOwnerMode" variable name ([`set -u`](https://github.com/docker-library/redmine/blob/7c0163067f16063562b8c7a8d2d2778561d1d7c3/docker-entrypoint.sh#L3) would've caught this 🙈😢).
This might be the solution to https://github.com/docker-library/redmine/issues/358
> Add missing assets directory

- 5.1/alpine3.21/docker-entrypoint.sh
- 5.1/alpine3.22/docker-entrypoint.sh
- 5.1/bookworm/docker-entrypoint.sh
- 6.0/alpine3.21/docker-entrypoint.sh
- 6.0/alpine3.22/docker-entrypoint.sh
- 6.0/bookworm/docker-entrypoint.sh
- docker-entrypoint.sh
This helps with having a separate sidekiq container without hacks (see what I have to use currently and the comment improvements:
``` yaml
sidekiq:
image: 'redmine:6.0.6'
pull_policy: 'never'
command: sh -c '/docker-entrypoint.sh rake --version && gosu redmine bundle exec sidekiq'
env_file:
- './data/redmine/config/.env'
volumes:
- type: 'bind'
source: './data/redmine/config/configuration.yml'
target: '/usr/src/redmine/config/configuration.yml'
depends_on:
mysql:
condition: 'service_healthy'
redis:
condition: 'service_healthy'
```
As you see atm I have to trigger `/docker-entrypoint.sh rake --version` so it sets the DB etc, this can be avoided if you consider "bundle" as a redmine command.
> Also consider "bundle" to be likely redmine

- generate-stackbrew-library.sh
This removes `arm32v6` (alpine) for 6.1 and above.
The builds are timing out on our build servers (after 3 hours) and the node is constantly at 100% CPU after the first 5-10 minutes. 😞 But I can locally build an `arm32v6` image via qemu user-mode in just 8 minutes. 😕 We don't have anything concurrently on the node, so it has a "dedicated" 8 vCPUs.
I'm not sure what to check to find a real solution.
Failing (timeout):
```console
Fetching doorkeeper-i18n 5.2.7
Installing doorkeeper-i18n 5.2.7
Cancelling nested steps due to timeout
Sending interrupt signal to process
#12 CANCELED
ERROR: failed to solve: Canceled: context canceled
script returned exit code 1
```
Local build:
```console
$ time docker build --platform linux/arm/v6 --progress=plain --build-arg BUILDKIT_DOCKERFILE_CHECK=skip=all …
```
> Drop arm32v6 for 6.1+
